# Generated by Django 5.1.1 on 2024-09-26 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(max_length=255)),
                ("task_description", models.CharField(max_length=1023)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "task_assign_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="tasks", to="category.taskcategory"
                    ),
                ),
            ],
        ),
    ]
